/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as PlayCategoryRouteImport } from './routes/play.$category'
import { Route as PlayCategoryIndexRouteImport } from './routes/play.$category.index'
import { Route as PlayCategorySubcategoryRouteImport } from './routes/play.$category.$subcategory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategoryRoute = PlayCategoryRouteImport.update({
  id: '/play/$category',
  path: '/play/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategoryIndexRoute = PlayCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayCategoryRoute,
} as any)
const PlayCategorySubcategoryRoute = PlayCategorySubcategoryRouteImport.update({
  id: '/$subcategory',
  path: '/$subcategory',
  getParentRoute: () => PlayCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/admin/import': typeof AdminImportRoute
  '/play/$category': typeof PlayCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/play/$category/$subcategory': typeof PlayCategorySubcategoryRoute
  '/play/$category/': typeof PlayCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/admin/import': typeof AdminImportRoute
  '/admin': typeof AdminIndexRoute
  '/play/$category/$subcategory': typeof PlayCategorySubcategoryRoute
  '/play/$category': typeof PlayCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/admin/import': typeof AdminImportRoute
  '/play/$category': typeof PlayCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/play/$category/$subcategory': typeof PlayCategorySubcategoryRoute
  '/play/$category/': typeof PlayCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/admin/import'
    | '/play/$category'
    | '/admin/'
    | '/play/$category/$subcategory'
    | '/play/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/admin/import'
    | '/admin'
    | '/play/$category/$subcategory'
    | '/play/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/admin/import'
    | '/play/$category'
    | '/admin/'
    | '/play/$category/$subcategory'
    | '/play/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  AdminImportRoute: typeof AdminImportRoute
  PlayCategoryRoute: typeof PlayCategoryRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category': {
      id: '/play/$category'
      path: '/play/$category'
      fullPath: '/play/$category'
      preLoaderRoute: typeof PlayCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category/': {
      id: '/play/$category/'
      path: '/'
      fullPath: '/play/$category/'
      preLoaderRoute: typeof PlayCategoryIndexRouteImport
      parentRoute: typeof PlayCategoryRoute
    }
    '/play/$category/$subcategory': {
      id: '/play/$category/$subcategory'
      path: '/$subcategory'
      fullPath: '/play/$category/$subcategory'
      preLoaderRoute: typeof PlayCategorySubcategoryRouteImport
      parentRoute: typeof PlayCategoryRoute
    }
  }
}

interface PlayCategoryRouteChildren {
  PlayCategorySubcategoryRoute: typeof PlayCategorySubcategoryRoute
  PlayCategoryIndexRoute: typeof PlayCategoryIndexRoute
}

const PlayCategoryRouteChildren: PlayCategoryRouteChildren = {
  PlayCategorySubcategoryRoute: PlayCategorySubcategoryRoute,
  PlayCategoryIndexRoute: PlayCategoryIndexRoute,
}

const PlayCategoryRouteWithChildren = PlayCategoryRoute._addFileChildren(
  PlayCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  AdminImportRoute: AdminImportRoute,
  PlayCategoryRoute: PlayCategoryRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
