/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlayCategoryRouteImport } from './routes/play.$category'
import { Route as PlayCategorySubcategoryRouteImport } from './routes/play.$category.$subcategory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategoryRoute = PlayCategoryRouteImport.update({
  id: '/play/$category',
  path: '/play/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategorySubcategoryRoute = PlayCategorySubcategoryRouteImport.update({
  id: '/$subcategory',
  path: '/$subcategory',
  getParentRoute: () => PlayCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/play/$category': typeof PlayCategoryRouteWithChildren
  '/play/$category/$subcategory': typeof PlayCategorySubcategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/play/$category': typeof PlayCategoryRouteWithChildren
  '/play/$category/$subcategory': typeof PlayCategorySubcategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/play/$category': typeof PlayCategoryRouteWithChildren
  '/play/$category/$subcategory': typeof PlayCategorySubcategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/play/$category'
    | '/play/$category/$subcategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/play/$category'
    | '/play/$category/$subcategory'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/play/$category'
    | '/play/$category/$subcategory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  PlayCategoryRoute: typeof PlayCategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category': {
      id: '/play/$category'
      path: '/play/$category'
      fullPath: '/play/$category'
      preLoaderRoute: typeof PlayCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category/$subcategory': {
      id: '/play/$category/$subcategory'
      path: '/$subcategory'
      fullPath: '/play/$category/$subcategory'
      preLoaderRoute: typeof PlayCategorySubcategoryRouteImport
      parentRoute: typeof PlayCategoryRoute
    }
  }
}

interface PlayCategoryRouteChildren {
  PlayCategorySubcategoryRoute: typeof PlayCategorySubcategoryRoute
}

const PlayCategoryRouteChildren: PlayCategoryRouteChildren = {
  PlayCategorySubcategoryRoute: PlayCategorySubcategoryRoute,
}

const PlayCategoryRouteWithChildren = PlayCategoryRoute._addFileChildren(
  PlayCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  PlayCategoryRoute: PlayCategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
