CREATE TYPE public.question_progress_state AS ENUM ('shown_unanswered', 'seen_answered');

CREATE TABLE public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id text NOT NULL UNIQUE,
  category text NOT NULL,
  question text NOT NULL,
  option_a text NOT NULL,
  option_b text NOT NULL,
  option_c text NOT NULL,
  option_d text NOT NULL,
  correct_answer text NOT NULL CHECK (correct_answer IN ('A', 'B', 'C', 'D')),
  difficulty text,
  detail text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.questions TO authenticated;
GRANT ALL ON public.questions TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.questions_id_seq TO service_role;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in visitors can read questions"
  ON public.questions FOR SELECT TO authenticated USING (true);

CREATE TABLE public.question_progress (
  user_id uuid NOT NULL,
  question_id text NOT NULL REFERENCES public.questions(question_id) ON DELETE CASCADE,
  state public.question_progress_state NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, question_id)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.question_progress TO authenticated;
GRANT ALL ON public.question_progress TO service_role;
ALTER TABLE public.question_progress ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Visitors can read their own progress"
  ON public.question_progress FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Visitors can create their own progress"
  ON public.question_progress FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Visitors can update their own progress"
  ON public.question_progress FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Visitors can delete their own progress"
  ON public.question_progress FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;
CREATE TRIGGER questions_set_updated_at BEFORE UPDATE ON public.questions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER question_progress_set_updated_at BEFORE UPDATE ON public.question_progress
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.available_question_counts()
RETURNS TABLE(category text, available_count bigint)
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public AS $$
  SELECT q.category, count(*)::bigint
  FROM public.questions q
  WHERE NOT EXISTS (
    SELECT 1 FROM public.question_progress p
    WHERE p.user_id = auth.uid()
      AND p.question_id = q.question_id
      AND p.state = 'seen_answered'
  )
  GROUP BY q.category
  ORDER BY q.category;
$$;

CREATE OR REPLACE FUNCTION public.start_question_set(requested_category text, set_size integer DEFAULT 10)
RETURNS SETOF public.questions
LANGUAGE plpgsql VOLATILE SECURITY INVOKER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'An anonymous session is required';
  END IF;

  RETURN QUERY
  WITH chosen AS (
    SELECT q.question_id
    FROM public.questions q
    WHERE q.category = requested_category
      AND NOT EXISTS (
        SELECT 1 FROM public.question_progress p
        WHERE p.user_id = auth.uid()
          AND p.question_id = q.question_id
          AND p.state = 'seen_answered'
      )
    ORDER BY random()
    LIMIT LEAST(GREATEST(set_size, 1), 10)
  ), marked AS (
    INSERT INTO public.question_progress (user_id, question_id, state)
    SELECT auth.uid(), chosen.question_id, 'shown_unanswered'
    FROM chosen
    ON CONFLICT (user_id, question_id)
    DO UPDATE SET state = 'shown_unanswered', updated_at = now()
    WHERE public.question_progress.state <> 'seen_answered'
    RETURNING question_progress.question_id
  )
  SELECT q.* FROM public.questions q
  JOIN chosen ON chosen.question_id = q.question_id
  ORDER BY random();
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_question_answered(answered_question_id text)
RETURNS void
LANGUAGE plpgsql VOLATILE SECURITY INVOKER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'An anonymous session is required';
  END IF;

  INSERT INTO public.question_progress (user_id, question_id, state)
  VALUES (auth.uid(), answered_question_id, 'seen_answered')
  ON CONFLICT (user_id, question_id)
  DO UPDATE SET state = 'seen_answered', updated_at = now();
END;
$$;

GRANT EXECUTE ON FUNCTION public.available_question_counts() TO authenticated;
GRANT EXECUTE ON FUNCTION public.start_question_set(text, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_question_answered(text) TO authenticated;
INSERT INTO public.questions (question_id, category, question, option_a, option_b, option_c, option_d, correct_answer, difficulty, detail) VALUES
('CAP-001', 'Capitals', 'What is the capital of France?', 'Lyon', 'Paris', 'Marseille', 'Nice', 'B', NULL, 'Paris has been the seat of French power since the Capetian kings settled the Ile de la Cite, the little island in the Seine where the city first curled into being.'),
('CAP-002', 'Capitals', 'What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 'C', NULL, 'Sydney and Melbourne quarrelled so bitterly over which deserved to be capital that the young nation built Canberra from nothing in the bush between them, a deliberate act of refusing to choose.'),
('CAP-003', 'Capitals', 'What is the capital of Canada?', 'Toronto', 'Vancouver', 'Montreal', 'Ottawa', 'D', NULL, 'Ottawa was chosen partly because it sat on the border of English and French Canada, and partly because its inland position made it harder for an American army to reach.'),
('CAP-004', 'Capitals', 'What is the capital of Brazil?', 'Rio de Janeiro', 'Brasilia', 'Sao Paulo', 'Salvador', 'B', NULL, 'Brasilia was conjured out of empty highland and opened in 1960, a whole capital planned and built in under four years where there had been only savanna.'),
('CAP-005', 'Capitals', 'What is the capital of Turkey?', 'Istanbul', 'Izmir', 'Ankara', 'Bursa', 'C', NULL, 'Istanbul is the grander and older city, yet Ataturk moved the capital to Ankara in 1923, turning the new republic to face inward rather than toward the imperial past on the Bosphorus.'),
('CAP-006', 'Capitals', 'Which city is the administrative (executive) capital of South Africa?', 'Cape Town', 'Pretoria', 'Bloemfontein', 'Johannesburg', 'B', NULL, 'South Africa keeps three capitals so that no single city holds every lever of power. Pretoria administers, Cape Town legislates, and Bloemfontein judges.'),
('CAP-007', 'Capitals', 'What is the constitutional capital of Bolivia?', 'La Paz', 'Santa Cruz', 'Sucre', 'Cochabamba', 'C', NULL, 'Sucre is the constitutional capital and the home of the supreme court, though the government and legislature actually sit far higher up in La Paz, the highest seat of government in the world.'),
('CAP-008', 'Capitals', 'Which city serves as the capital of Switzerland?', 'Zurich', 'Geneva', 'Bern', 'Basel', 'C', NULL, 'Switzerland names no capital anywhere in its constitution. Bern merely serves as the federal city, the quiet compromise of a country wary of raising any one of its own above the rest.'),
('CAP-009', 'Capitals', 'What is the capital of Nigeria?', 'Lagos', 'Abuja', 'Kano', 'Ibadan', 'B', NULL, 'Lagos was the crowded coastal capital until 1991, when Nigeria moved its seat of government to the purpose-built city of Abuja, set in the country''s centre to belong to no single region.'),
('CAP-010', 'Capitals', 'What is the capital of New Zealand?', 'Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'B', NULL, 'Auckland is far larger, but windswept Wellington holds the title, and sitting near the bottom of the North Island it is the southernmost capital of any sovereign country on Earth.'),
('CAP-011', 'Capitals', 'What is the capital of Kazakhstan?', 'Almaty', 'Shymkent', 'Astana', 'Karaganda', 'C', NULL, 'The capital was renamed Nur-Sultan in 2019 and then changed back to Astana in 2022. An older name for the same city, Akmola, means white grave in Kazakh, which is a hard thing to forget once you have heard it.'),
('CAP-012', 'Capitals', 'What is the political capital of Burundi?', 'Bujumbura', 'Gitega', 'Ngozi', 'Muyinga', 'B', NULL, 'Burundi named Gitega its political capital by law in 2019, leaving Bujumbura as the economic capital and largest city. A capital, it turns out, can be declared years before the government has finished actually moving there.'),
('CAP-013', 'Capitals', 'What is the capital of Myanmar?', 'Yangon', 'Mandalay', 'Naypyidaw', 'Bago', 'C', NULL, 'Naypyidaw was built in secret and unveiled in 2005, a vast planned capital of twenty-lane highways that stand mostly empty, a city sized for a crowd that has never quite arrived.'),
('CAP-014', 'Capitals', 'What is the capital of the United States?', 'New York', 'Washington, D.C.', 'Philadelphia', 'Boston', 'B', NULL, 'Washington was carved as a neutral district from land ceded by Maryland and Virginia so that the capital would sit in no state at all. Philadelphia and New York both served as temporary capitals before it was ready.'),
('CAP-015', 'Capitals', 'What is the capital of Palau?', 'Koror', 'Ngerulmud', 'Melekeok', 'Airai', 'B', NULL, 'Ngerulmud may be the least peopled capital on the planet, a small cluster of government buildings on the island of Babeldaob watched over by far more jungle than people.'),
('GEO-001', 'Geography', 'Which river is most commonly regarded as the longest in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B', NULL, 'By long convention the Nile wears the crown, yet the Amazon presses its claim and, by some measurements, may run longer still. Rivers, it turns out, are difficult to hold a ruler against.'),
('GEO-002', 'Geography', 'What is the largest country in the world by area?', 'Canada', 'China', 'Russia', 'United States', 'C', NULL, 'Russia covers around seventeen million square kilometres and stretches across eleven time zones, so that when workers in the west are sitting down to breakfast, those in the far east are already asleep.'),
('GEO-003', 'Geography', 'What is the largest ocean on Earth?', 'Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean', 'C', NULL, 'The Pacific is so vast that it covers roughly a third of the planet and holds more water than all the land on Earth could displace if you dropped it in.'),
('GEO-004', 'Geography', 'The deepest known point in the ocean lies in which trench?', 'Tonga Trench', 'Puerto Rico Trench', 'Mariana Trench', 'Java Trench', 'C', NULL, 'The Challenger Deep in the Mariana Trench sinks almost eleven kilometres down. Lower Everest into it and more than two kilometres of dark water would still close over the summit.'),
('GEO-005', 'Geography', 'What is the highest uninterrupted waterfall in the world?', 'Niagara Falls', 'Angel Falls', 'Victoria Falls', 'Iguazu Falls', 'B', NULL, 'Angel Falls in Venezuela drops nearly a kilometre from the lip of a flat-topped mountain called Auyan-tepui, and in the dry season much of it turns to mist long before it reaches the ground.'),
('GEO-006', 'Geography', 'What is the largest desert in the world?', 'Sahara', 'Arabian Desert', 'Antarctic Desert', 'Gobi Desert', 'C', NULL, 'A desert is defined by how little rain falls, not by heat, so the frozen silence of Antarctica is the largest desert on Earth. The Sahara, for all its dunes, comes only second.'),
('GEO-007', 'Geography', 'What is the highest mountain above sea level?', 'K2', 'Mount Everest', 'Kangchenjunga', 'Denali', 'B', NULL, 'Everest reaches 8,849 metres above the sea. Measured instead from its base, the Hawaiian volcano Mauna Kea is taller still, though most of it hides beneath the Pacific.'),
('GEO-008', 'Geography', 'What is the largest island in the world?', 'New Guinea', 'Greenland', 'Borneo', 'Madagascar', 'B', NULL, 'Greenland is the largest island by a wide margin. Australia is bigger yet, but geographers count it as a continent rather than an island, which is the only reason Greenland holds the record.'),
('GEO-009', 'Geography', 'What is the largest lake in the world by surface area?', 'Lake Superior', 'Caspian Sea', 'Lake Victoria', 'Lake Baikal', 'B', NULL, 'The Caspian is called a sea and behaves like one, salty and vast, yet it is landlocked, which makes it the largest lake on Earth. Names, as ever, are a poor guide to geography.'),
('GEO-010', 'Geography', 'What is the deepest lake in the world?', 'Caspian Sea', 'Lake Tanganyika', 'Lake Baikal', 'Lake Superior', 'C', NULL, 'Older and deeper than any other, Siberia''s Lake Baikal holds close to a fifth of all the unfrozen fresh water in the world, sealed in a rift where the continent is slowly pulling itself apart.'),
('GEO-011', 'Geography', 'What is the longest mountain range on land?', 'Rocky Mountains', 'The Andes', 'Himalayas', 'Great Dividing Range', 'B', NULL, 'The Andes run some seven thousand kilometres down the western edge of South America. The longest range of all is longer still, but it is the mid-ocean ridge, hidden almost entirely beneath the sea.'),
('GEO-012', 'Geography', 'What is the smallest country in the world?', 'Monaco', 'Nauru', 'Vatican City', 'San Marino', 'C', NULL, 'Vatican City covers less than half a square kilometre, small enough to walk across in a morning, yet it is a fully sovereign state with its own post office, railway, and head of state.'),
('GEO-013', 'Geography', 'What is the largest continent by area?', 'Africa', 'Asia', 'North America', 'Antarctica', 'B', NULL, 'Asia is the largest continent by far and also the most peopled, home to well over half of everyone alive, from the Arabian deserts in the west to the Pacific coast in the east.'),
('GEO-014', 'Geography', 'Which is the only sea on Earth with no land boundary?', 'Coral Sea', 'Sargasso Sea', 'Caspian Sea', 'Red Sea', 'B', NULL, 'The Sargasso Sea has no shore at all. It is bounded not by land but by four ocean currents that turn slowly around it, and sailors once feared its still, weed-strewn waters as a place where becalmed ships went to be forgotten.');
